# Generated by Django 5.1.1 on 2024-10-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_container_created_at_container_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b64_photo', models.TextField()),
            ],
        ),
    ]
