# Generated by Django 5.1.1 on 2024-10-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pgp_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
