# Generated by Django 5.1.1 on 2024-10-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_pgp_public_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='pgp_private_key',
            new_name='user_pgp_public_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pgp_public_key',
        ),
    ]
